# Generated by Django 3.1.7 on 2021-04-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.IntegerField()),
                ('lines', models.CharField(max_length=300)),
                ('syllabic_transliteration', models.TextField()),
                ('broad_transliteration', models.TextField()),
                ('text_translation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('CTH', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=5000)),
                ('publication', models.CharField(max_length=5000)),
                ('duplicate', models.CharField(blank=True, max_length=100, null=True)),
                ('text_index', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.TextField()),
                ('translation', models.TextField()),
                ('lemma', models.TextField()),
                ('pos', models.CharField(max_length=500)),
                ('synt_role', models.CharField(blank=True, max_length=500, null=True)),
                ('word_order', models.IntegerField()),
                ('dependency', models.IntegerField()),
                ('group_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.clause')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.meta')),
            ],
        ),
    ]
